xp_ip: 192.168.0.3
xp_send_port: 49001 # X-Plane sends UDP on this port
xp_recv_port: 49000 # X-Plane receives UDP on this port
xp_packet_header: CCCCC
xp_packet_data_s: lffffffff
xp_no: -999 # X-Plane's value 

serial: /dev/tty.usbmodem411
baud: 9600
data_bits: 8
stop_bits: 1

